project_id = "tpoxhrbweavvjszlqryp"

[functions.ai-address-assistant]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = true

[functions.ai-address-assistant-v2]
verify_jwt = true

[functions.reset-addresses]
verify_jwt = true

[functions.geocode-address]
verify_jwt = true

[functions.upload-street-list]
verify_jwt = true

[functions.analyze-csv-structure]
verify_jwt = true

[functions.export-project-addresses]
verify_jwt = true

[functions.get-user-email]
verify_jwt = true
