import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { audio, existingText, improvementInstruction, context } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    let transcribedText = "";

    // If audio is provided, transcribe it first using Whisper
    if (audio) {
      console.log("Transcribing audio...");
      
      // Decode base64 audio
      const audioBuffer = Uint8Array.from(atob(audio), c => c.charCodeAt(0));
      
      // Create form data for Whisper API
      const formData = new FormData();
      const audioBlob = new Blob([audioBuffer], { type: 'audio/webm' });
      formData.append('file', audioBlob, 'audio.webm');
      formData.append('model', 'whisper-1');
      formData.append('language', 'de');

      const whisperResponse = await fetch('https://api.openai.com/v1/audio/transcriptions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
        },
        body: formData,
      });

      if (!whisperResponse.ok) {
        const error = await whisperResponse.text();
        console.error('Whisper API error:', error);
        throw new Error('Audio transcription failed');
      }

      const whisperData = await whisperResponse.json();
      transcribedText = whisperData.text;
      console.log("Transcribed text:", transcribedText);
    }

    // Build the prompt for text generation
    let systemPrompt = `Du bist ein erfahrener Projekt-Manager, der ansprechende Ausschreibungstexte für Vertriebsprojekte erstellt.

Deine Aufgabe ist es, einen motivierenden Infotext für eine Projekt-Ausschreibung zu erstellen, der Vertriebspartner (genannt "Raketen") begeistert und zum Mitmachen animiert.

Der Text soll folgende Aspekte berücksichtigen:
- Provider: Welcher Provider ist das?
- Besonderheiten: Was macht das Projekt besonders?
- Mehrwert: Warum lohnt es sich, bei diesem Projekt zu starten?
- Vorteile: Was sind die spezifischen Vorteile?

Schreibe den Text professionell, aber enthusiastisch. Nutze eine klare Struktur mit Absätzen. Der Text soll verkaufen, aber nicht übertrieben wirken.`;

    let userPrompt = "";

    if (improvementInstruction) {
      // Improvement mode
      systemPrompt += "\n\nDu verbesserst einen bestehenden Text basierend auf den gegebenen Anweisungen.";
      userPrompt = `Bestehender Text:\n${existingText}\n\nVerbesserungsanweisung: ${improvementInstruction}\n\nBitte verbessere den Text entsprechend der Anweisung.`;
    } else if (transcribedText) {
      // Generation from transcription
      userPrompt = `Basierend auf folgender Spracheingabe, erstelle einen strukturierten Ausschreibungstext:\n\n${transcribedText}`;
      
      if (context?.providerName) {
        userPrompt += `\n\nProvider: ${context.providerName}`;
      }
      if (context?.projectName) {
        userPrompt += `\nProjekt: ${context.projectName}`;
      }
      if (context?.areaName) {
        userPrompt += `\nGebiet: ${context.areaName}`;
      }
    } else {
      throw new Error('Neither audio nor improvement instruction provided');
    }

    console.log("Generating text with AI...");

    // Call Lovable AI to generate the text
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.7,
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI API error:', errorText);
      throw new Error('AI generation failed');
    }

    const aiData = await aiResponse.json();
    const generatedText = aiData.choices[0]?.message?.content;

    if (!generatedText) {
      throw new Error('No text generated by AI');
    }

    console.log("Text generated successfully");

    return new Response(
      JSON.stringify({ 
        generatedText,
        transcribedText: transcribedText || undefined
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    console.error('Error in generate-tender-info:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
